### ISSUE TITLE
试用了一下

### ISSUE THREAD

**Issue by zhaokun78** [Jonham/weapp-component-tabbar#3]
试用了一下，感觉侵入性还是过于强了些，于是放弃了

**Comment by autoool** [comment]
@zhaokun78 请教你一个问题，这个库我在其它页面使用index同样的代码，就报错了。VM3900:1 pages/logs/logs.js 出现脚本错误或者未正确调用 Page()。在app.js里面放到第一个的页面，不会报这个错误。你有好的解决办法吗？自定义的tabBar。我的qq 274676067,还希望尽快得到你的答复呢。

**Comment by hu-qi** [comment]
不明觉厉  各位大大还有好的建议吗

**Comment by Jonham** [comment]
@chaozaiai 我晚一点查一下。最近比较忙。
