### ISSUE TITLE
same code in  logs  with index page,but there is error.

### ISSUE THREAD

**Issue by autoool** [Jonham/weapp-component-tabbar#5]
sdk uncaught third Error 
 Cannot read property 'setData' of undefined 
 TypeError: Cannot read property 'setData' of undefined
    at setTabbarData (http://127.0.0.1:50034/appservice/pages/template/tabbar.js:181:14)
    at http://127.0.0.1:50034/appservice/pages/logs/logs.js:53:27
    at require (http://127.0.0.1:50034/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:50034/appservice/appservice:1176:9
console.error @ VM2570:1
(anonymous) @ WAService.js:4
(anonymous) @ WAService.js:4
a @ VM2575 appservice:1154
window.onerror @ VM2570:1
VM2592 appservice:1179 Mon Mar 19 2018 09:52:43 GMT+0800 (中国标准时间) page 编译错误
VM2570:1 pages/logs/logs.js 出现脚本错误或者未正确调用 Page()

**Comment by Jonham** [comment]
晚一点我查一下。

**Comment by Jonham** [comment]
_isPageInited = true;的问题。已处理。
