### ISSUE TITLE
未找到 app.json 中的定义的 pages "pages/canvas/canvas" 对应的 WXML 文件

### ISSUE THREAD

**Issue by ChunrunHan** [Jonham/weapp-component-tabbar#6]
{
  "pages":[
    "pages/canvas/canvas",
    "pages/index/index",
    "pages/logs/logs"
  ],
  "window":{
    "backgroundTextStyle":"light",
    "navigationBarBackgroundColor": "#fff",
    "navigationBarTitleText": "weapp-component-tabbar",
    "navigationBarTextStyle":"black",
    "enablePullDownRefresh": "true"
  }
}

**Comment by Jonham** [comment]
`pages/canvas/canvas` 是当年本地测试用的一个页面，以删除。
感谢
