### ISSUE TITLE
onLoad函数获取不了跨页面传值

### ISSUE THREAD

**Issue by Cherokeeli** [Jonham/weapp-component-tabbar#7]
使用的时候发现组件中提供的init的参数中onLoad()有些问题，不能像小程序默认生命周期函数onLoad(options)函数获取options参数，自己在tabbar.js中暂时这么解决的
```
onLoad() {
            // 调用用户定义的生命周期函数
            _super.onLoad.apply(this, arguments);

            // 保存this到_page
            _page = this
        },
```

**Comment by Jonham** [comment]
已采纳。
https://github.com/Jonham/weapp-component-tabbar/commit/8f62bb8d350f5d2167b93188e4a78bef38544493

**Comment by Jonham** [comment]
谢谢
